// <auto-generated />
using System;
using Get_5_Day_Forecast.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Get_5_Day_Forecast.Migrations
{
    [DbContext(typeof(WeatherContext))]
    partial class WeatherContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Get_5_Day_Forecast.Model.AvgDayForecast", b =>
                {
                    b.Property<Guid>("ForecastId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AvgMaxTemp");

                    b.Property<decimal>("AvgMinTemp");

                    b.Property<string>("City");

                    b.Property<string>("Date");

                    b.HasKey("ForecastId");

                    b.ToTable("AvgDayForecasts");
                });
#pragma warning restore 612, 618
        }
    }
}
